### ISSUE TITLE
Codes shared between characters

### ISSUE THREAD

**Issue by Bostmaster** [DemmyDemon/demmylock#3]
If the server has a multi characters system, the codes is shared across characters.

Exemple: You are a police officer, you get the code for the armory and use it. 
Now you want to play on your other character, that character can now open the lock with just pressing [E]. 

I don't see a fix for it without implementing some db stuff. But it can be nice for other users to know that it can be an issue

**Comment by DemmyDemon** [comment]
You are correct, the system does not have any way to detect any sort of multi-character system.

You can modify it to save/load the key with some sort of prefix, and to get that prefix from an event.
Then you just have your multi-character system emit that even then there is a character selection.

Please note that I will _not_ be making this modification, as I'm not an active FiveM resource developer at this time.

Edit:  It'd be nice if you did a pull request, though, in case others want the same feature.
